name       : spice-protocol
version    : 0.12.10
release    : 5
source     :
    - http://www.spice-space.org/download/releases/spice-protocol-0.12.10.tar.bz2 : 788f0d7195bec5b14371732b562eb55ca82712aab12273b0e87529fb30532efb
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
