name       : spice-protocol
version    : 0.12.14
release    : 9
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.12.14.tar.bz2 : 20350bc4309039fdf0d29ee4fd0033cde27bccf33501e13b3c1befafde9d0c9c
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
