name       : spice-protocol
version    : 0.14.4
release    : 17
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.14.4.tar.xz : 04ffba610d9fd441cfc47dfaa135d70096e60b1046d2119d8db2f8ea0d17d912
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
