name       : spice-protocol
version    : 0.14.2
release    : 14
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.14.2.tar.xz : 8f3a63c8b68300dffe36f2e75eac57afa1e76d5d80af760fd138a0b3f44cf1e9
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
