name       : spice-protocol
version    : 0.12.13
release    : 8
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.12.13.tar.bz2 : 89ee11b202d2268e061788e6ace114e1ff18c7620ae64d1ca3aba252ee7c9933
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
