name       : spice-protocol
version    : 0.12.15
release    : 13
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.12.15.tar.bz2 : 8b4db23baa4b1337a50d049d9bf43f932331dd95f204836c0ce46c4962306419
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
