name       : spice-protocol
version    : 0.12.9
release    : 2
source     :
    - http://www.spice-space.org/download/releases/spice-protocol-0.12.9.tar.bz2 : 290cf834dd156014d229b474e98006265ab9c5f63b4c471ea3b2cf8b2ff37876
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
patterns   :
    - /*
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
