name       : spice-protocol
version    : 0.12.12
release    : 6
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.12.12.tar.bz2 : 17abdc2743b5d44b0f4423b61c44aafe9f2078c27218aeea78c2d02a5c409d03
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
