name       : spice-protocol
version    : 0.14.3
release    : 15
source     :
    - https://www.spice-space.org/download/releases/spice-protocol-0.14.3.tar.xz : f986e5bc2a1598532c4897f889afb0df9257ac21c160c083703ae7c8de99487a
license    : BSD-3-Clause
summary    : Headers for SPICE protocol
description: |
    Headers for SPICE protocol
component  : desktop.library
patterns   :
    - /*
replaces   :
    - spice-protocol-devel
rundeps    :
    - python-six
    - pyparsing
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
